### ISSUE TITLE
storage factory lesson

### ISSUE THREAD

**Issue by musteehadee** [PatrickAlphaC/simple-storage-fcc#7]
hi, i am having issue with my compiler, it is showing me error while not highlighting the exact place in the environment. i cant find it
![Screenshot (33)](https://user-images.githubusercontent.com/98564090/197310372-a172a4b8-836c-4382-b5b9-680017e72d04.png)

**Comment by Anthrax420** [comment]
Its on the import line it should be ./simpleStorage . Your S is written in caps

**Comment by musteehadee** [comment]
Thanks a lot 🙏🙏

**Comment by nenadsky** [comment]
Hi! When defining mapping, we bind _favouriteNumber to a _name. And if we have multiple persons with same name (for example John), what will function nameToFavouriteNumber return, and how to access other values?

**Comment by Insane-9** [comment]
hey why don't you close the issue??
