### ISSUE TITLE
Storage factory issue 

### ISSUE THREAD

**Issue by Anthrax420** [PatrickAlphaC/simple-storage-fcc#8]
Cant understand what i typed wrong or am doing wrong 
![WhatsApp Image 2022-10-27 at 6 42 34 PM](https://user-images.githubusercontent.com/116183886/198301510-1bba3977-cae8-44d9-8307-a97d6a7f7679.jpeg)

**Comment by Divyans-chauhan** [comment]
SimpleStorage must be the type of variable you've created. Here the type should be the contract you've named in simple.sol code. 

In the tutorials patrick has named it SimpleStorage and it dont seem you have used the same name. Thats why the error

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/

Thanks!
