### ISSUE TITLE
Potentially should be constant/view/pure but is not error in the code

### ISSUE THREAD

**Issue by ShivSankar** [PatrickAlphaC/simple-storage-fcc#9]
I'm getting the warning which is highlighted in yellowish color when I' m using this code. I understand that the issue in addPeople function but can anyone tell me how to get rid of it?

![simpleStorageIssue1](https://user-images.githubusercontent.com/12861776/201865937-0d41aae7-5b4a-4321-aec7-305288e61024.PNG)

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-py
